[package]
name = "driver"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
maschine_library.workspace = true
hidapi.workspace = true
num.workspace = true
midly.workspace = true
midir.workspace = true
clap.workspace = true
