[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.dependencies]
hidapi = { version = "2.6.3" }
num = { version = "0.4.3" }
num-derive = { version = "0.4.2" }
num-traits = { version = "0.2.19" }
midly = { version = "0.5.3" }
midir = { version = "0.10.2", features = ["default"] }
