notemaps = [61, 62, 63, 64, 57, 58, 59, 60, 53, 54, 55, 56, 49, 50, 51, 52]
client_name = "Maschine Mikro MK3"
port_name = "Maschine Mikro MK3 MIDI Out"

osc_ip = "127.0.0.1"
osc_port = 57120
osc_listen_port = 57121


[button_configs.Shift]
mode = "trigger"

[button_configs.Play]
mode = "trigger"

[button_configs.Stop]
mode = "trigger"

[button_configs.Rec]
mode = "toggle"

[button_configs.Group]
mode = "toggle"
group_id = 1

[button_configs.NoteRepeat]
mode = "toggle"
group_id = 1

[button_configs.Lock]
mode = "toggle"
group_id = 1

[button_configs.Auto]
mode = "toggle"
group_id = 1

[button_configs.Pitch]
mode = "toggle"
group_id = 2

[button_configs.Mod]
mode = "toggle"
group_id = 2

[button_configs.Perform]
mode = "toggle"
group_id = 2

[button_configs.Notes]
mode = "toggle"
group_id = 2

[button_configs.Pattern]
mode = "toggle"
group_id = 3

[button_configs.Scene]
mode = "toggle"
group_id = 3

[button_configs.Events]
mode = "toggle"
group_id = 3

[button_configs.Variation]
mode = "toggle"
group_id = 3

[button_configs.Duplicate]
mode = "toggle"
group_id = 3

[button_configs.Select]
mode = "toggle"
group_id = 3