[package]
name = "maschine_library"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
hidapi.workspace = true
num.workspace = true
num-derive.workspace = true
num-traits.workspace = true

[package.metadata.cargo-shear]
ignored = ["num-traits"]